title: Pooja Sharma Portfolio
description: Technical Writing Portfolio
theme: just-the-docs

url: "https://pujasharma68-ui.github.io"
baseurl: ""

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
